language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
install: pip install pytest spec coverage
script: py.test rotate-backups.py --spec --cov=.
notifications:
  email:
    recipients:
      - dr@netsyno.com
